version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqs-processor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ahl4sx6nrxq4"
s3_prefix = "sqs-processor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
